### PR TITLE
Update Solutions.tex

### PR DESCRIPTION
**Pull request by YizheCrystalXu**
Hi, Dr. Reeder

Sorry about that, I just fixed it, and hopefully it can be merged right now.

### CODE REVIEW

**Comment by RonReeder** [comment]
It doesn't look like you changed the 06.17.tex file...

**Comment by YizheCrystalXu** [comment]
Should I deleted the command with "\begin{exercise 1}"? I just did that

**Comment by RonReeder** [comment]
Yes, \begin{exercise 1} and \end{exercise 1} need to go away.  Also, \me and \md require packages that aren't installed.  One option would be to do partial derivatives this way: http://www.maths.tcd.ie/~dwilkins/LaTeXPrimer/Calculus.html.  Also, I think you have a \begin{proof} without a \end{proof} and this would also require another package.  You are welcome to add packages you need to solutions.tex.  Or you can find another way to code it.

**Comment by YizheCrystalXu** [comment]
I think I got it finally, please check.

**Comment by RonReeder** [comment]
If you've updated your repository, you'll need to create another pull request.

**Comment by YizheCrystalXu** [comment]
Ok, I just created another pull request, it is #31

**Pull request closed without merging**
